language: python

sudo: false

dist: xenial
services:
  - xvfb

env:
  global:
    # Doctr deploy key for pyoceans/python-oceans
    - secure: "MohzYBz9P2VQhPTISFMV+X4Jj+E1RrrZt+39L+wc6G+uQp+cWn/gKMg2HaqH7Naed/Z4VNdcoKbT1XA+masTuLXERKtdCIi9ad7cdlaDapmnoKZ1eloZRZltQ7xzBYtMQYrgRYe4URG910pfbwRFKC0pg0+ektE5QGyEUTzHxUw="

matrix:
  fast_finish: true
  include:
    - name: "python-3.7"
      env: PY=3.7
    - name: "python-3.8"
      env: PY=3.8
    - name: "doctests"
      env: PY=3
    - name: "coding_standards"
      env: PY=3
    - name: "tarball"
      env: PY=3
    - name: "docs"
      env: PY=3

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
    source activate TEST
    conda info --all

install:
  - pip install -e . --no-deps --force-reinstall

script:
  - if [[ $TRAVIS_JOB_NAME == python-* ]]; then
      cp -r tests/ /tmp ;
      pushd /tmp && pytest -n 2 -rxs --cov=oceans tests && popd ;
    fi

  - if [[ $TRAVIS_JOB_NAME == 'tarball' ]]; then
      pip wheel . -w dist --no-deps ;
      check-manifest --verbose ;
      twine check dist/* ;
    fi

  - if [[ $TRAVIS_JOB_NAME == doctests ]]; then
      pytest -vv oceans --doctest-modules ;
    fi

  - if [[ $TRAVIS_JOB_NAME == 'coding_standards' ]]; then
      pytest --flake8 -m flake8 ;
    fi

  - |
    if [[ $TRAVIS_JOB_NAME == 'docs' ]]; then
      set -e
      conda install doctr
      pushd docs
      make clean html linkcheck
      popd
      python -m doctr deploy . --key-path github_deploy_key.enc --built-docs docs/build/html/
    fi

doctr:
  require-master: true
  sync: False

deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: "HifofjCDgTUP3hv0C8xD411JBCIp7VziSE5SiD9ZXo9CGo/rnr2rxtIcA9QDHfwO0n1iK26AhUbmeUURecn7+GjvvwCsbN3y21zfx0/D6KCSCvfEuJBJG2uAZqbNBFkT5//96umsavVngp0vNzOASDCljBgC9t5X0r1JnybQUro="
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: pyoceans/python-oceans
    tags: true
    all_branches: master
    condition: '$TRAVIS_JOB_NAME == "tarball"'
